### ISSUE TITLE
Confusing email sending. Sends emails to the wrong email address.

### ISSUE THREAD

**Issue by DemianParkhomenko** [cloudipsp/node-js-sdk#4]
Reproduce: 
1. Make a request
```js 
const CloudIpsp = require('../lib')

const fondy = new CloudIpsp(
  {
    merchantId: 1396424,
    secretKey: 'test'
  }
)

const data = {
  order_desc: 'test order',
  currency: 'USD',
  amount: '1000',
  sender_email: 'first@gmail.com'  // 👀
}

fondy.Checkout(data).then(data => {
  console.log(data)
}).catch((error) => {
  console.log(error)
})
```
2. Enter another email on the checkout_url page

![image](https://user-images.githubusercontent.com/95881717/228315436-47241130-1a54-47a4-a654-ad23675fd352.png)

3. The email will be sent to `first@gmail.com`. 

Expected: 
The email will be sent to `second@gmail.com` or a field for email in checkout_url page to be read-only.

**Comment by has-well** [comment]
Hello, sender_email is pre-defined email, if customer want to change his email they can do this on checkout page. If you want, use email on response page or callback URL you can set it to merchant data

**Comment by DemianParkhomenko** [comment]
Thank you, but have you tried to reproduce [it](https://github.com/cloudipsp/node-js-sdk/issues/4#issue-1644379073)? Does it send an email to `second@gmail.com`?
